kind: Template
apiVersion: v1
metadata:
  name: gocd-server
  annotations:
    openshift.io/display-name: GoCD Server
    description: 'Create a GoCD Server'
    tags: ci-cd,gocd
message: ''
labels:
  template: gocd-server
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: gocd-server
    annotations:
      description: ImageStream for gocd-server
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: gocd-server
  spec:
    runPolicy: Serial
    triggers:
    - type: ConfigChange
    source:
      type: Dockerfile
      dockerfile: |-
        FROM atbentley/openshift-gocd-server:latest
        ENV GOCD_AGENT_SECRET=${GOCD_AGENT_SECRET}
    strategy:
      type: Docker
      env:
      - name: "GOCD_AGENT_SECRET"
        value: "${GOCD_AGENT_SECRET}"
    output:
      to:
        kind: ImageStreamTag
        name: gocd-server:latest
- kind: DeploymentConfig

  apiVersion: v1
  metadata:
    name: gocd-server
  spec:
    replicas: 1
    selector:
      app: gocd-server
      deploymentconfig: gocd-server
    template:
      metadata:
        labels:
          app: gocd-server
          deploymentconfig: gocd-server
      spec:
        containers:
        - name: gocd-server
          image: gocd-server
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - gocd-server
        from:
          kind: ImageStreamTag
          name: gocd-server:latest
    strategy:
      type: Rolling
    paused: false
    revisionHistoryLimit: 2
    minReadySeconds: 0
- kind: "Service" 
  apiVersion: "v1"
  metadata:
    name: "gocd-server"
    annotations:
      description: ""
  spec:
    ports:
      - name: "http"
        port: 8153
        targetPort: 8153
      - name: "https"
        port: 8154
        targetPort: 8154
    selector:
      app: "gocd-server"
- kind: Template
  apiVersion: v1
  metadata:
    name: gocd-agent
    annotations:
      openshift.io/display-name: GoCD Agent
      description: ''
      tags: ci-cd,gocd
  message: ''
  labels:
    template: gocd-agent
  objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: gocd-agent-${NAME}
      annotations:
        description: ImageStream for gocd-agent-${NAME}
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: gocd-agent-${NAME}
    spec:
      runPolicy: Serial
      triggers:
      - type: ConfigChange
      source:
        type: Dockerfile
        dockerfile: |-
          FROM atbentley/openshift-gocd-agent:latest
          RUN yum install -y ${EXTRA_PACKAGES} && yum clean all -y
          ENV GO_SERVER_URL=${GO_SERVER_URL}
          ENV GOCD_AGENT_SECRET=${GOCD_AGENT_SECRET}
      strategy:
        type: Docker
        env:
        - name: EXTRA_PACKAGES
          value: "${EXTRA_PACKAGES}"
        - name: GO_SERVER_URL
          value: "${GO_SERVER_URL}"
        - name: "GOCD_AGENT_SECRET"
          value: "${GOCD_AGENT_SECRET}"
      output:
        to:
          kind: ImageStreamTag
          name: gocd-agent-${NAME}:latest
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: gocd-agent-${NAME}
    spec:
      replicas: 1
      selector:
        app: gocd-agent-${NAME}
        deploymentconfig: gocd-agent-${NAME}
      template:
        metadata:
          labels:
            app: gocd-agent-${NAME}
            deploymentconfig: gocd-agent-${NAME}
        spec:
          containers:
          - name: gocd-agent-${NAME}
            image: gocd-agent-${NAME}
      triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
          - gocd-agent-${NAME}
          from:
            kind: ImageStreamTag
            name: gocd-agent-${NAME}:latest
      strategy:
        type: Rolling
      paused: false
      revisionHistoryLimit: 2
      minReadySeconds: 0
  parameters:
  - name: NAME
    displayName: Name
    description: The name to give this agent, will take the form of gocd-agent-$NAME.
    required: true
    value: ''
  - name: GO_SERVER_URL
    displayName: Go server URL
    description: The URL for the Go server, needs to start with https:// and end with /go
    required: true
    value: ''
  - name: EXTRA_PACKAGES
    displayName: Extra packages
    description: A space seperated list of yum packages to install on the agent.
    required: true
    value: ''
parameters:
  - name: GOCD_AGENT_SECRET
    displayName: GoCD agent secret
    description: "A secret for allowing agents to authenticate with the server automatically"
    generate: expression
    from: "[a-zA-Z0-9]{16}"
